spring:
  application:
    name: USER-SERVICE
server:
  port: 8082
  servlet:
    context-path: /user
# eureka server registry for user service as client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/admin/eureka/

resilience4j:
  bulkhead:
    instances:
      catalogServiceName:
        # Max amount of time a thread should be blocked for when attempting to enter a saturated bulkhead.
        maxWaitDuration: 2s
        # Max amount of parallel concurrent executions allowed by the bulkhead
        maxConcurrentCalls: 3

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # health, circuitbreakers
  endpoint:
    health:
      show-details: always